### ISSUE TITLE
Texte/Inhalte für Veröffentlichung Google Play Store vorbereiten

### ISSUE THREAD

**Issue by Letterus** [luki-ev/synod-android#19]
Inhalte:

1. Beschreibung der App - Hinweis auf Projekt und Verantwortliche: Titel, Kurzbeschreibung (80Z.), Langbeschreibung (4000Z.) Deutsch und Englisch
2. Altersbeschränkung (keine - mit Nachfrage bei den Eltern)
3. App-Zugriff: Registrierung ist für Anmeldung notwendig: Für Google einen Testaccount anlegen

Vorbereitung: https://pad.luki.org/p/Synod_Android_Google_Play

**Comment by csett86** [comment]
Ich habe im Pad einen Vorschlag gemacht, basierend auf den Apple App Store-Text und librechurch.org

**Comment by csett86** [comment]
App ist im Play-Store, daher erledigt
