### ISSUE TITLE
App stürzt bei Klick auf "Nutzungsbedingungen" ab

### ISSUE THREAD

**Issue by Letterus** [luki-ev/synod-android#4]
Im Menü "Hilfe & Über", eingeloggter Benutzer.

**Comment by Letterus** [comment]
Ebeneso "Datenschutzerklärung"

**Comment by Letterus** [comment]
Ebenso "Nutzungshinweise von Drittanbietern"

**Comment by vorletzter** [comment]
Bug kommt von einer alten appcompat Version. Update auf 1.2.0-alpha02 hat es behoben. 

vgl. https://stackoverflow.com/questions/58028821/webview-crash-on-android-5-5-1-api-21-22-resourcesnotfoundexception-string-r

**Comment by Letterus** [comment]
Gefixt mit f8063130307eaf926f6085ac260d038f7444d07c.
