### ISSUE TITLE
App zwecks Pushnachrichten mit Push Server und Google FCM verheiraten

### ISSUE THREAD

**Issue by Letterus** [luki-ev/synod-android#8]

**Comment by dontub** [comment]
TODO:
1. google-services.json für debug und release Variante auf https://console.firebase.google.com/ erstellen und die vorhandenen Dateien (`vector/src/gplay/debug/google-services.json` bzw. `vector/src/gplay/release/google-services.json`) ersetzen.
2. Server Keys für beide Varianten als `api_key` in der `sygnal.yaml` unseres Sygnal Push Gateways eintragen.

**Comment by Letterus** [comment]
Ist soweit rund. Danke @dontub!
